# Project information

site_name: AWS Transfer for SFTP Lab
site_description: 'En este laboratorio usted aprenderá a utilizar la herramienta de CloudEndure llevando a cabo todas las tareas necesarias para la migración de un servidor hacia el entorno de nube de AWS. Para efectos de este laboratorio, usted desplegará un servidor Linux con Apache en una instancia de EC2 ubicada en la región de N. Virigina que simulará ser un servidor que se encuentra en su centro de datos o con algún proveedor de servicios de nube. Dentro de este servidor usted instalará el agente de CloudEndure para llevar a cabo la migración a la región de N. California.'
#site_author: 'josepenu@amazon.com'
site_url: 'http://transfer.oldschool.cloud'

# Repository
#repo_name: 'name'
repo_url: 'https://github.com/josemp-git/awstransferlab'

google_analytics: ['UA-147241276-2', 'transfer.oldschool.cloud']

# Copyright
copyright: '&copy; 2019 - José Peñúñuri '

extra:
  social:
    - type: 'home'
      link: 'http://transfer.oldschool.cloud'
    - type: 'twitter'
      link: 'https://twitter.com/jose_penunuri'

nav:
    - Inicio: index.md
    - 1. Creación de bucket de S3: s3bucket.md
    - 2. Creación de políticas de IAM.: politicasiam.md
    - 3. Creación de rol de IAM: roliam.md
    - 4. Creación del servidor SFTP: sftpserver.md
    - 5. Creación de usuarios del el servidor SFTP: users.md
    - 6. Conéctese a su servidor SFTP: connect.md
theme:
  name: 'material'
  palette:
    primary: 'Black'
    accent: 'Indigo'
  logo:
    icon: 'cloud_done'
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pyembed.markdown
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg